version: '3'

services:
    apache:
        image: httpd:2.4
        volumes:
            - ${DOCKER_APP_HOST}:/var/www/html
            - ./${DOCKER_FOLDER_NAME}/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
        depends_on:
            - php

    nginx:
        image: nginx:1.13
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${DOCKER_APP_HOST}:/var/www/html
            - ./${DOCKER_FOLDER_NAME}/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - apache

    php:
        build:
            ./${DOCKER_FOLDER_NAME}/php
        volumes:
            - ${DOCKER_APP_HOST}:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_MYSQL_ROOT_PASSWORD}
        volumes:
            - ./${DOCKER_FOLDER_NAME}/databases:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1