version: '3'

services:
    apache:
        image: httpd:2.4
        volumes:
            - ${APP_HOST}:/var/www/html
            - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
        depends_on:
            - php

    nginx:
        image: nginx:1.13
        ports:
            - 80:80
        volumes:
            - ${APP_HOST}:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - apache

    php:
        build:
            ./php
        volumes:
            - ${APP_HOST}:/var/www/html
            - /mail/msmtprc:/etc/msmtprc
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1